<?php
$fieldTypeAttribute = [
    'text'=>[
        'default_value'=>null,
        'placeholder'=>'',
        'prepend'=>'',
        'append'=>'',
        'formatting'=>'html',
        'character_limit'=>'',
    ],
    'textarea'=>[
        'default_value'=>null,
        'placeholder'=>'',
        'rows'=>8,
        'formatting'=>'html',
        'character_limit'=>'',
    ],
    'number'=>[
        'default_value'=>null,
        'placeholder'=>'',
        'prepend'=>'',
        'append'=>'',
        'minimum_value'=>'',
        'maximum_value'=>'',
        'step_size'=>'',
    ],
    'email'=>[
        'default_value'=>null,
        'placeholder'=>'',
        'prepend'=>'',
        'append'=>'',
    ],
    'password'=>[
        'placeholder'=>'',
        'prepend'=>'',
        'append'=>'',
    ],
    'editor'=>[
        'default_value'=>null,
        'toolbar'=>'full',
        'media'=>'1',
    ],
    'image'=>[
        'width'=>'',
        'height'=>'',
        'min_width'=>'',
        'max_width'=>'',
        'min_height'=>'',
        'max_height'=>'',
        'ratio_width'=>'',
        'ratio_height'=>'',
        'multi_img'=>'0',
    ],
    'asset-file'=>[
    ],
    'select'=>[
        'default_value'=>null,
        'choices'=>'',
        'allow_null'=>'0',
        'multiple'=>'0',
    ],
    'checkbox'=>[
    	'default_value'=>'',
    	'choices'=>'',
    	'layout'=>'vertical'
    ],
    'radio'=>[
         'default_value'=>null,
        'choices'=>'',
        'layout'=>'vertical',
        'other_choice'=>'0',
        'save_other_choice'=>'0',
    ],
    'true_false'=>[
        'default_value'=>'',
        'message'=>'',
    ],
    
    'relationship_onetoone'=>[
        'object'=>'',
    ],
    'relationship_onetomany'=>[
        'object'=>'',
    ],
    'relationship_manytomany'=>[
        'object'=>'',
    ],
    'repeater'=>[
    	'layout'=>'table',
    	'button_label'=>'Add Row',
    	'maximum_rows'=>0,
    	'minimum_rows'=>0,
    	'sub_fields'=>''
	],
	'flexible'=>[
		'button_label'=>'Add Row',
		'maximum_rows'=>0,
		'minimum_rows'=>0,
		'templates'=>''
	],
    'group'=>[
        'layout'=>'table',
        'sub_fields'=>''
    ],
    'tab'=>[

    ],
    'menu'=>[

    ],
    'link'=>[

    ],
];